being bad and pushing!
jbohlig/Project-1 pull request #1
Opened 2019-09-28 18:16 UTC by MalinkaMell

updating readme

2019-09-28 18:23 UTC, jbohlig requested changes
I don't like this file name

2019-09-28 18:30 UTC, Unevenmageta commented
Looks Good

2019-09-28 18:30 UTC, Unevenmageta approved these changes

2019-09-28 18:33 UTC, Unevenmageta approved these changes
is this working

2019-10-02 01:12 UTC, jbohlig approved these changes

2019-10-02 01:12 UTC, merged